[package]
name = "contour_macros"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
ignore = "0.4.22"
itertools = "0.12.0"
proc-macro2 = "1.0.70"
quote = "1.0.33"
syn = { version = "2.0.40", features = ["full"] }
